### ISSUE TITLE
Won't Initialize

### ISSUE THREAD

**Issue by ferazambuja** [vogelrh/AirSense#1]
Hi,
Here is what I get when I run the app:

> ./airsense -d
Application Starting
I2C Address: Primary
Disable PMS5003: 0
Broker: test.mosquitto.org
Port: 1883
Topic: AirSenseData/raspberrypizero
Sensor ID: raspberrypizero
Sample Multiplier: 2
Initializing MQTT communications
Initializing sensor communications
Initializing BSEC library
>

Also is there a way to use declare the mqtt password?

Thanks!

**Comment by vogelrh** [comment]
Are you compiling the code as-is from GitHub on the Pi Zero or are you using the prepack script? If you are compiling on the Pi Zero, you will need to change the ARCH parameter in make.config to PIZero_ArmV6-32bits.

The current version has not been configured to accept username and password for MQTT. The library I use is capable of it and it is on my list of improvements. In the mean time, you could always hard-code the username and password in the mqtt-connect statement for simple testing purposes if you have a particular broker you need to connect to that requires it.

**Comment by ferazambuja** [comment]
Got it to work I forgot about the i2c address, I have an enviro+ that has a BME280 at the address 76.
Thanks
