### ISSUE TITLE
MQTT User and Password

### ISSUE THREAD

**Issue by ferazambuja** [vogelrh/AirSense#2]
I'm not so used to how MQTT-C handles user and password.
Do you mind giving an idea of how to hardcoded?

Keep the great work.

**Comment by vogelrh** [comment]
In airsense.c at line 541 (latest commit) you need to modify the line:
`mqtt_connect(&client, sensor_id, NULL, NULL, 0, NULL, NULL, 0, 400);`
to:
`mqtt_connect(&client, sensor_id, NULL, NULL, 0, <username>, <password>, 0, 400);`

you can find more details [here](https://liambindle.ca/MQTT-C/group__api.html).

**Comment by ferazambuja** [comment]
Thanks, I will give it a try.
