### ISSUE TITLE
stat'ing binary file bsec_iaq.state: No such file or directory

### ISSUE THREAD

**Issue by ferazambuja** [vogelrh/AirSense#5]
I've checked the documentation but I couldn't get it where is the default file path for AirSense.

I'm using the default CONFIG_DIR='.' on 
https://github.com/vogelrh/AirSense/blob/53a8d34b77e5f05131e7a5a62491bd0d31972c3f/make.config#L22

Thanks

**Comment by vogelrh** [comment]
The make file will create an empty .state file and the correct .config file in the top level project directory. The airsense.c code will expect to find the file in the directory the program was executed in (its working directory). Make sure the .state and the .config files are present in the working directory. For example if you have cd'ed into the top level project directory, you can type $ ./bin/airsense .... to execute the code and it should find the files. The make file found in the prepackaged code tar ball will move/create these files in the airsense/bin directory on the target machine.
